version: '3'
services:
  ros_lecture_melodic:
    container_name: ros_lecture_melodic_202307
    image: kmiyawaki20/ros1_melodic_user_ubuntu_lxde_202307
    volumes:
      - ubuntu:/home/ubuntu
    ports:
      - "6080:80"
      - "5901:5901"
    environment:
      - USER=ubuntu
      - RESOLUTION=1280x800
      - TZ=Asia/Tokyo
    tty: true

volumes:
  ubuntu:
